apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micro-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: microservices.local
    http:
      paths:
      - path: /books
        pathType: ImplementationSpecific
        backend:
          service:
            name: book-service
            port:
              number: 80
      - path: /users
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service
            port:
              number: 80
